name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies on web and api directories
        run: |
          cd web && sudo npm install
          cd ../api && sudo npm install && sudo npm install jsdom
      - name: Run tests on web
        run: |-
          cd web
          sudo npm run test
      - name: Run tests on server
        run: |-
          cd api
          sudo npm run test